// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: object_detection/protos/faster_rcnn_box_coder.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Tensorflow.Models.ObjectDetection.Protos {

  /// <summary>Holder for reflection information generated from object_detection/protos/faster_rcnn_box_coder.proto</summary>
  public static partial class FasterRcnnBoxCoderReflection {

    #region Descriptor
    /// <summary>File descriptor for object_detection/protos/faster_rcnn_box_coder.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FasterRcnnBoxCoderReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjNvYmplY3RfZGV0ZWN0aW9uL3Byb3Rvcy9mYXN0ZXJfcmNubl9ib3hfY29k",
            "ZXIucHJvdG8SF29iamVjdF9kZXRlY3Rpb24ucHJvdG9zImEKEkZhc3RlclJj",
            "bm5Cb3hDb2RlchIPCgd5X3NjYWxlGAEgASgCEg8KB3hfc2NhbGUYAiABKAIS",
            "FAoMaGVpZ2h0X3NjYWxlGAMgASgCEhMKC3dpZHRoX3NjYWxlGAQgASgCYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Tensorflow.Models.ObjectDetection.Protos.FasterRcnnBoxCoder), global::Tensorflow.Models.ObjectDetection.Protos.FasterRcnnBoxCoder.Parser, new[]{ "YScale", "XScale", "HeightScale", "WidthScale" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Configuration proto for FasterRCNNBoxCoder. See
  /// box_coders/faster_rcnn_box_coder.py for details.
  /// </summary>
  public sealed partial class FasterRcnnBoxCoder : pb::IMessage<FasterRcnnBoxCoder> {
    private static readonly pb::MessageParser<FasterRcnnBoxCoder> _parser = new pb::MessageParser<FasterRcnnBoxCoder>(() => new FasterRcnnBoxCoder());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<FasterRcnnBoxCoder> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tensorflow.Models.ObjectDetection.Protos.FasterRcnnBoxCoderReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FasterRcnnBoxCoder() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FasterRcnnBoxCoder(FasterRcnnBoxCoder other) : this() {
      yScale_ = other.yScale_;
      xScale_ = other.xScale_;
      heightScale_ = other.heightScale_;
      widthScale_ = other.widthScale_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FasterRcnnBoxCoder Clone() {
      return new FasterRcnnBoxCoder(this);
    }

    /// <summary>Field number for the "y_scale" field.</summary>
    public const int YScaleFieldNumber = 1;
    private float yScale_;
    /// <summary>
    /// Scale factor for anchor encoded box center.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float YScale {
      get { return yScale_; }
      set {
        yScale_ = value;
      }
    }

    /// <summary>Field number for the "x_scale" field.</summary>
    public const int XScaleFieldNumber = 2;
    private float xScale_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float XScale {
      get { return xScale_; }
      set {
        xScale_ = value;
      }
    }

    /// <summary>Field number for the "height_scale" field.</summary>
    public const int HeightScaleFieldNumber = 3;
    private float heightScale_;
    /// <summary>
    /// Scale factor for anchor encoded box height.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float HeightScale {
      get { return heightScale_; }
      set {
        heightScale_ = value;
      }
    }

    /// <summary>Field number for the "width_scale" field.</summary>
    public const int WidthScaleFieldNumber = 4;
    private float widthScale_;
    /// <summary>
    /// Scale factor for anchor encoded box width.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float WidthScale {
      get { return widthScale_; }
      set {
        widthScale_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as FasterRcnnBoxCoder);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(FasterRcnnBoxCoder other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(YScale, other.YScale)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(XScale, other.XScale)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(HeightScale, other.HeightScale)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(WidthScale, other.WidthScale)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (YScale != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(YScale);
      if (XScale != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(XScale);
      if (HeightScale != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(HeightScale);
      if (WidthScale != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(WidthScale);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (YScale != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(YScale);
      }
      if (XScale != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(XScale);
      }
      if (HeightScale != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(HeightScale);
      }
      if (WidthScale != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(WidthScale);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (YScale != 0F) {
        size += 1 + 4;
      }
      if (XScale != 0F) {
        size += 1 + 4;
      }
      if (HeightScale != 0F) {
        size += 1 + 4;
      }
      if (WidthScale != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(FasterRcnnBoxCoder other) {
      if (other == null) {
        return;
      }
      if (other.YScale != 0F) {
        YScale = other.YScale;
      }
      if (other.XScale != 0F) {
        XScale = other.XScale;
      }
      if (other.HeightScale != 0F) {
        HeightScale = other.HeightScale;
      }
      if (other.WidthScale != 0F) {
        WidthScale = other.WidthScale;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            YScale = input.ReadFloat();
            break;
          }
          case 21: {
            XScale = input.ReadFloat();
            break;
          }
          case 29: {
            HeightScale = input.ReadFloat();
            break;
          }
          case 37: {
            WidthScale = input.ReadFloat();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
