// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: object_detection/protos/grid_anchor_generator.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Tensorflow.Models.ObjectDetection.Protos {

  /// <summary>Holder for reflection information generated from object_detection/protos/grid_anchor_generator.proto</summary>
  public static partial class GridAnchorGeneratorReflection {

    #region Descriptor
    /// <summary>File descriptor for object_detection/protos/grid_anchor_generator.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GridAnchorGeneratorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjNvYmplY3RfZGV0ZWN0aW9uL3Byb3Rvcy9ncmlkX2FuY2hvcl9nZW5lcmF0",
            "b3IucHJvdG8SF29iamVjdF9kZXRlY3Rpb24ucHJvdG9zIrUBChNHcmlkQW5j",
            "aG9yR2VuZXJhdG9yEg4KBmhlaWdodBgBIAEoBRINCgV3aWR0aBgCIAEoBRIV",
            "Cg1oZWlnaHRfc3RyaWRlGAMgASgFEhQKDHdpZHRoX3N0cmlkZRgEIAEoBRIV",
            "Cg1oZWlnaHRfb2Zmc2V0GAUgASgFEhQKDHdpZHRoX29mZnNldBgGIAEoBRIO",
            "CgZzY2FsZXMYByADKAISFQoNYXNwZWN0X3JhdGlvcxgIIAMoAmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Tensorflow.Models.ObjectDetection.Protos.GridAnchorGenerator), global::Tensorflow.Models.ObjectDetection.Protos.GridAnchorGenerator.Parser, new[]{ "Height", "Width", "HeightStride", "WidthStride", "HeightOffset", "WidthOffset", "Scales", "AspectRatios" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Configuration proto for GridAnchorGenerator. See
  /// anchor_generators/grid_anchor_generator.py for details.
  /// </summary>
  public sealed partial class GridAnchorGenerator : pb::IMessage<GridAnchorGenerator> {
    private static readonly pb::MessageParser<GridAnchorGenerator> _parser = new pb::MessageParser<GridAnchorGenerator>(() => new GridAnchorGenerator());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GridAnchorGenerator> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tensorflow.Models.ObjectDetection.Protos.GridAnchorGeneratorReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GridAnchorGenerator() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GridAnchorGenerator(GridAnchorGenerator other) : this() {
      height_ = other.height_;
      width_ = other.width_;
      heightStride_ = other.heightStride_;
      widthStride_ = other.widthStride_;
      heightOffset_ = other.heightOffset_;
      widthOffset_ = other.widthOffset_;
      scales_ = other.scales_.Clone();
      aspectRatios_ = other.aspectRatios_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GridAnchorGenerator Clone() {
      return new GridAnchorGenerator(this);
    }

    /// <summary>Field number for the "height" field.</summary>
    public const int HeightFieldNumber = 1;
    private int height_;
    /// <summary>
    /// Anchor height in pixels.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Height {
      get { return height_; }
      set {
        height_ = value;
      }
    }

    /// <summary>Field number for the "width" field.</summary>
    public const int WidthFieldNumber = 2;
    private int width_;
    /// <summary>
    /// Anchor width in pixels.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Width {
      get { return width_; }
      set {
        width_ = value;
      }
    }

    /// <summary>Field number for the "height_stride" field.</summary>
    public const int HeightStrideFieldNumber = 3;
    private int heightStride_;
    /// <summary>
    /// Anchor stride in height dimension in pixels.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int HeightStride {
      get { return heightStride_; }
      set {
        heightStride_ = value;
      }
    }

    /// <summary>Field number for the "width_stride" field.</summary>
    public const int WidthStrideFieldNumber = 4;
    private int widthStride_;
    /// <summary>
    /// Anchor stride in width dimension in pixels.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int WidthStride {
      get { return widthStride_; }
      set {
        widthStride_ = value;
      }
    }

    /// <summary>Field number for the "height_offset" field.</summary>
    public const int HeightOffsetFieldNumber = 5;
    private int heightOffset_;
    /// <summary>
    /// Anchor height offset in pixels.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int HeightOffset {
      get { return heightOffset_; }
      set {
        heightOffset_ = value;
      }
    }

    /// <summary>Field number for the "width_offset" field.</summary>
    public const int WidthOffsetFieldNumber = 6;
    private int widthOffset_;
    /// <summary>
    /// Anchor width offset in pixels.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int WidthOffset {
      get { return widthOffset_; }
      set {
        widthOffset_ = value;
      }
    }

    /// <summary>Field number for the "scales" field.</summary>
    public const int ScalesFieldNumber = 7;
    private static readonly pb::FieldCodec<float> _repeated_scales_codec
        = pb::FieldCodec.ForFloat(58);
    private readonly pbc::RepeatedField<float> scales_ = new pbc::RepeatedField<float>();
    /// <summary>
    /// List of scales for the anchors.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<float> Scales {
      get { return scales_; }
    }

    /// <summary>Field number for the "aspect_ratios" field.</summary>
    public const int AspectRatiosFieldNumber = 8;
    private static readonly pb::FieldCodec<float> _repeated_aspectRatios_codec
        = pb::FieldCodec.ForFloat(66);
    private readonly pbc::RepeatedField<float> aspectRatios_ = new pbc::RepeatedField<float>();
    /// <summary>
    /// List of aspect ratios for the anchors.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<float> AspectRatios {
      get { return aspectRatios_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GridAnchorGenerator);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GridAnchorGenerator other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Height != other.Height) return false;
      if (Width != other.Width) return false;
      if (HeightStride != other.HeightStride) return false;
      if (WidthStride != other.WidthStride) return false;
      if (HeightOffset != other.HeightOffset) return false;
      if (WidthOffset != other.WidthOffset) return false;
      if(!scales_.Equals(other.scales_)) return false;
      if(!aspectRatios_.Equals(other.aspectRatios_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Height != 0) hash ^= Height.GetHashCode();
      if (Width != 0) hash ^= Width.GetHashCode();
      if (HeightStride != 0) hash ^= HeightStride.GetHashCode();
      if (WidthStride != 0) hash ^= WidthStride.GetHashCode();
      if (HeightOffset != 0) hash ^= HeightOffset.GetHashCode();
      if (WidthOffset != 0) hash ^= WidthOffset.GetHashCode();
      hash ^= scales_.GetHashCode();
      hash ^= aspectRatios_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Height != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Height);
      }
      if (Width != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Width);
      }
      if (HeightStride != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(HeightStride);
      }
      if (WidthStride != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(WidthStride);
      }
      if (HeightOffset != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(HeightOffset);
      }
      if (WidthOffset != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(WidthOffset);
      }
      scales_.WriteTo(output, _repeated_scales_codec);
      aspectRatios_.WriteTo(output, _repeated_aspectRatios_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Height != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Height);
      }
      if (Width != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Width);
      }
      if (HeightStride != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(HeightStride);
      }
      if (WidthStride != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(WidthStride);
      }
      if (HeightOffset != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(HeightOffset);
      }
      if (WidthOffset != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(WidthOffset);
      }
      size += scales_.CalculateSize(_repeated_scales_codec);
      size += aspectRatios_.CalculateSize(_repeated_aspectRatios_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GridAnchorGenerator other) {
      if (other == null) {
        return;
      }
      if (other.Height != 0) {
        Height = other.Height;
      }
      if (other.Width != 0) {
        Width = other.Width;
      }
      if (other.HeightStride != 0) {
        HeightStride = other.HeightStride;
      }
      if (other.WidthStride != 0) {
        WidthStride = other.WidthStride;
      }
      if (other.HeightOffset != 0) {
        HeightOffset = other.HeightOffset;
      }
      if (other.WidthOffset != 0) {
        WidthOffset = other.WidthOffset;
      }
      scales_.Add(other.scales_);
      aspectRatios_.Add(other.aspectRatios_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Height = input.ReadInt32();
            break;
          }
          case 16: {
            Width = input.ReadInt32();
            break;
          }
          case 24: {
            HeightStride = input.ReadInt32();
            break;
          }
          case 32: {
            WidthStride = input.ReadInt32();
            break;
          }
          case 40: {
            HeightOffset = input.ReadInt32();
            break;
          }
          case 48: {
            WidthOffset = input.ReadInt32();
            break;
          }
          case 58:
          case 61: {
            scales_.AddEntriesFrom(input, _repeated_scales_codec);
            break;
          }
          case 66:
          case 69: {
            aspectRatios_.AddEntriesFrom(input, _repeated_aspectRatios_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
