// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: tensorflow/core/framework/types.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Tensorflow {

  /// <summary>Holder for reflection information generated from tensorflow/core/framework/types.proto</summary>
  public static partial class TypesReflection {

    #region Descriptor
    /// <summary>File descriptor for tensorflow/core/framework/types.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TypesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiV0ZW5zb3JmbG93L2NvcmUvZnJhbWV3b3JrL3R5cGVzLnByb3RvEgp0ZW5z",
            "b3JmbG93IjkKD1NlcmlhbGl6ZWREVHlwZRImCghkYXRhdHlwZRgBIAEoDjIU",
            "LnRlbnNvcmZsb3cuRGF0YVR5cGUqqgYKCERhdGFUeXBlEg4KCkRUX0lOVkFM",
            "SUQQABIMCghEVF9GTE9BVBABEg0KCURUX0RPVUJMRRACEgwKCERUX0lOVDMy",
            "EAMSDAoIRFRfVUlOVDgQBBIMCghEVF9JTlQxNhAFEgsKB0RUX0lOVDgQBhIN",
            "CglEVF9TVFJJTkcQBxIQCgxEVF9DT01QTEVYNjQQCBIMCghEVF9JTlQ2NBAJ",
            "EgsKB0RUX0JPT0wQChIMCghEVF9RSU5UOBALEg0KCURUX1FVSU5UOBAMEg0K",
            "CURUX1FJTlQzMhANEg8KC0RUX0JGTE9BVDE2EA4SDQoJRFRfUUlOVDE2EA8S",
            "DgoKRFRfUVVJTlQxNhAQEg0KCURUX1VJTlQxNhAREhEKDURUX0NPTVBMRVgx",
            "MjgQEhILCgdEVF9IQUxGEBMSDwoLRFRfUkVTT1VSQ0UQFBIOCgpEVF9WQVJJ",
            "QU5UEBUSDQoJRFRfVUlOVDMyEBYSDQoJRFRfVUlOVDY0EBcSEAoMRFRfRkxP",
            "QVRfUkVGEGUSEQoNRFRfRE9VQkxFX1JFRhBmEhAKDERUX0lOVDMyX1JFRhBn",
            "EhAKDERUX1VJTlQ4X1JFRhBoEhAKDERUX0lOVDE2X1JFRhBpEg8KC0RUX0lO",
            "VDhfUkVGEGoSEQoNRFRfU1RSSU5HX1JFRhBrEhQKEERUX0NPTVBMRVg2NF9S",
            "RUYQbBIQCgxEVF9JTlQ2NF9SRUYQbRIPCgtEVF9CT09MX1JFRhBuEhAKDERU",
            "X1FJTlQ4X1JFRhBvEhEKDURUX1FVSU5UOF9SRUYQcBIRCg1EVF9RSU5UMzJf",
            "UkVGEHESEwoPRFRfQkZMT0FUMTZfUkVGEHISEQoNRFRfUUlOVDE2X1JFRhBz",
            "EhIKDkRUX1FVSU5UMTZfUkVGEHQSEQoNRFRfVUlOVDE2X1JFRhB1EhUKEURU",
            "X0NPTVBMRVgxMjhfUkVGEHYSDwoLRFRfSEFMRl9SRUYQdxITCg9EVF9SRVNP",
            "VVJDRV9SRUYQeBISCg5EVF9WQVJJQU5UX1JFRhB5EhEKDURUX1VJTlQzMl9S",
            "RUYQehIRCg1EVF9VSU5UNjRfUkVGEHtCegoYb3JnLnRlbnNvcmZsb3cuZnJh",
            "bWV3b3JrQgtUeXBlc1Byb3Rvc1ABWkxnaXRodWIuY29tL3RlbnNvcmZsb3cv",
            "dGVuc29yZmxvdy90ZW5zb3JmbG93L2dvL2NvcmUvZnJhbWV3b3JrL3R5cGVz",
            "X2dvX3Byb3Rv+AEBYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Tensorflow.DataType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Tensorflow.SerializedDType), global::Tensorflow.SerializedDType.Parser, new[]{ "Datatype" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// (== suppress_warning documentation-presence ==)
  /// LINT.IfChange
  /// </summary>
  public enum DataType {
    /// <summary>
    /// Not a legal value for DataType.  Used to indicate a DataType field
    /// has not been set.
    /// </summary>
    [pbr::OriginalName("DT_INVALID")] DtInvalid = 0,
    /// <summary>
    /// Data types that all computation devices are expected to be
    /// capable to support.
    /// </summary>
    [pbr::OriginalName("DT_FLOAT")] DtFloat = 1,
    [pbr::OriginalName("DT_DOUBLE")] DtDouble = 2,
    [pbr::OriginalName("DT_INT32")] DtInt32 = 3,
    [pbr::OriginalName("DT_UINT8")] DtUint8 = 4,
    [pbr::OriginalName("DT_INT16")] DtInt16 = 5,
    [pbr::OriginalName("DT_INT8")] DtInt8 = 6,
    [pbr::OriginalName("DT_STRING")] DtString = 7,
    /// <summary>
    /// Single-precision complex
    /// </summary>
    [pbr::OriginalName("DT_COMPLEX64")] DtComplex64 = 8,
    [pbr::OriginalName("DT_INT64")] DtInt64 = 9,
    [pbr::OriginalName("DT_BOOL")] DtBool = 10,
    /// <summary>
    /// Quantized int8
    /// </summary>
    [pbr::OriginalName("DT_QINT8")] DtQint8 = 11,
    /// <summary>
    /// Quantized uint8
    /// </summary>
    [pbr::OriginalName("DT_QUINT8")] DtQuint8 = 12,
    /// <summary>
    /// Quantized int32
    /// </summary>
    [pbr::OriginalName("DT_QINT32")] DtQint32 = 13,
    /// <summary>
    /// Float32 truncated to 16 bits.  Only for cast ops.
    /// </summary>
    [pbr::OriginalName("DT_BFLOAT16")] DtBfloat16 = 14,
    /// <summary>
    /// Quantized int16
    /// </summary>
    [pbr::OriginalName("DT_QINT16")] DtQint16 = 15,
    /// <summary>
    /// Quantized uint16
    /// </summary>
    [pbr::OriginalName("DT_QUINT16")] DtQuint16 = 16,
    [pbr::OriginalName("DT_UINT16")] DtUint16 = 17,
    /// <summary>
    /// Double-precision complex
    /// </summary>
    [pbr::OriginalName("DT_COMPLEX128")] DtComplex128 = 18,
    [pbr::OriginalName("DT_HALF")] DtHalf = 19,
    [pbr::OriginalName("DT_RESOURCE")] DtResource = 20,
    /// <summary>
    /// Arbitrary C++ data types
    /// </summary>
    [pbr::OriginalName("DT_VARIANT")] DtVariant = 21,
    [pbr::OriginalName("DT_UINT32")] DtUint32 = 22,
    [pbr::OriginalName("DT_UINT64")] DtUint64 = 23,
    /// <summary>
    /// Do not use!  These are only for parameters.  Every enum above
    /// should have a corresponding value below (verified by types_test).
    /// </summary>
    [pbr::OriginalName("DT_FLOAT_REF")] DtFloatRef = 101,
    [pbr::OriginalName("DT_DOUBLE_REF")] DtDoubleRef = 102,
    [pbr::OriginalName("DT_INT32_REF")] DtInt32Ref = 103,
    [pbr::OriginalName("DT_UINT8_REF")] DtUint8Ref = 104,
    [pbr::OriginalName("DT_INT16_REF")] DtInt16Ref = 105,
    [pbr::OriginalName("DT_INT8_REF")] DtInt8Ref = 106,
    [pbr::OriginalName("DT_STRING_REF")] DtStringRef = 107,
    [pbr::OriginalName("DT_COMPLEX64_REF")] DtComplex64Ref = 108,
    [pbr::OriginalName("DT_INT64_REF")] DtInt64Ref = 109,
    [pbr::OriginalName("DT_BOOL_REF")] DtBoolRef = 110,
    [pbr::OriginalName("DT_QINT8_REF")] DtQint8Ref = 111,
    [pbr::OriginalName("DT_QUINT8_REF")] DtQuint8Ref = 112,
    [pbr::OriginalName("DT_QINT32_REF")] DtQint32Ref = 113,
    [pbr::OriginalName("DT_BFLOAT16_REF")] DtBfloat16Ref = 114,
    [pbr::OriginalName("DT_QINT16_REF")] DtQint16Ref = 115,
    [pbr::OriginalName("DT_QUINT16_REF")] DtQuint16Ref = 116,
    [pbr::OriginalName("DT_UINT16_REF")] DtUint16Ref = 117,
    [pbr::OriginalName("DT_COMPLEX128_REF")] DtComplex128Ref = 118,
    [pbr::OriginalName("DT_HALF_REF")] DtHalfRef = 119,
    [pbr::OriginalName("DT_RESOURCE_REF")] DtResourceRef = 120,
    [pbr::OriginalName("DT_VARIANT_REF")] DtVariantRef = 121,
    [pbr::OriginalName("DT_UINT32_REF")] DtUint32Ref = 122,
    [pbr::OriginalName("DT_UINT64_REF")] DtUint64Ref = 123,
  }

  #endregion

  #region Messages
  /// <summary>
  /// Represents a serialized tf.dtypes.Dtype
  /// </summary>
  public sealed partial class SerializedDType : pb::IMessage<SerializedDType>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SerializedDType> _parser = new pb::MessageParser<SerializedDType>(() => new SerializedDType());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SerializedDType> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tensorflow.TypesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SerializedDType() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SerializedDType(SerializedDType other) : this() {
      datatype_ = other.datatype_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SerializedDType Clone() {
      return new SerializedDType(this);
    }

    /// <summary>Field number for the "datatype" field.</summary>
    public const int DatatypeFieldNumber = 1;
    private global::Tensorflow.DataType datatype_ = global::Tensorflow.DataType.DtInvalid;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Tensorflow.DataType Datatype {
      get { return datatype_; }
      set {
        datatype_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SerializedDType);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SerializedDType other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Datatype != other.Datatype) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Datatype != global::Tensorflow.DataType.DtInvalid) hash ^= Datatype.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Datatype != global::Tensorflow.DataType.DtInvalid) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Datatype);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Datatype != global::Tensorflow.DataType.DtInvalid) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Datatype);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Datatype != global::Tensorflow.DataType.DtInvalid) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Datatype);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SerializedDType other) {
      if (other == null) {
        return;
      }
      if (other.Datatype != global::Tensorflow.DataType.DtInvalid) {
        Datatype = other.Datatype;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Datatype = (global::Tensorflow.DataType) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Datatype = (global::Tensorflow.DataType) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
